CREATE TABLE IF NOT EXISTS public.voc_cases (
    case_id text PRIMARY KEY,
    customer_name text,
    country text,
    voc_type text,
    voc_subtype text,
    priority text,
    customer_request text,
    original_mail_body text,
    responsible_departments text,
    received_at date,
    first_response_at date,
    containment_at text,
    root_cause_action_5d_at text,
    customer_reply_at text,
    final_status text,
    delay_stage text,
    delay_reason text,
    auto_close boolean,
    reactivated boolean,
    due_6d_at date,
    result_6d text,
    full_response_history text,
    customer_request_embedding text,
    original_mail_body_embedding text
);
